Repository spring-cloud/spring-cloud-consul, pull requests merged in 2021-03, with the labels that each got.

#710 Add quickstart section to docs.
  README.adoc
  docs/src/main/asciidoc/README.adoc
  docs/src/main/asciidoc/quickstart.adoc
  docs/src/main/asciidoc/spring-cloud-consul.adoc
Labels: documentation

#713 Path configuration ability
  docs/src/main/asciidoc/_configprops.adoc
  spring-cloud-consul-core/src/main/java/org/springframework/cloud/consul/ConsulAutoConfiguration.java
  spring-cloud-consul-core/src/main/java/org/springframework/cloud/consul/ConsulProperties.java
  spring-cloud-consul-core/src/test/java/org/springframework/cloud/consul/ConsulAutoConfigurationTests.java
Labels: in progress

#684 Adds support for multiple default query tags
  spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryClient.java
  spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryProperties.java
  spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/reactive/ConsulReactiveDiscoveryClient.java
  spring-cloud-consul-discovery/src/test/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryClientDefaultQueryTagTests.java
  spring-cloud-consul-discovery/src/test/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryClientQueryTagsTests.java
  spring-cloud-consul-discovery/src/test/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryClientServerListQueryTagTests.java
  spring-cloud-consul-discovery/src/test/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryPropertiesTests.java
  spring-cloud-consul-discovery/src/test/java/org/springframework/cloud/consul/discovery/reactive/ConsulReactiveDiscoveryClientTests.java
Labels: enhancement

#691 Add option for re-registration when ephemeral Consul is restarted
  docs/src/main/asciidoc/_configprops.adoc
  spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/HeartbeatProperties.java
  spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ReregistrationPredicate.java
  spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/TtlScheduler.java
  spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/serviceregistry/ConsulServiceRegistry.java
  spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/support/ConsulHeartbeatAutoConfiguration.java
  spring-cloud-consul-discovery/src/test/java/org/springframework/cloud/consul/discovery/ConsulHeartbeatTaskTests.java
Labels: in progress

#715 Use abstract config data post processor
  spring-cloud-consul-config/pom.xml
  spring-cloud-consul-config/src/main/java/org/springframework/cloud/consul/config/ConsulConfigDataMissingEnvironmentPostProcessor.java
  spring-cloud-consul-config/src/test/java/org/springframework/cloud/consul/config/ConsulConfigDataMissingEnvironmentPostProcessorTests.java
  spring-cloud-consul-config/src/test/java/org/springframework/cloud/consul/config/ConsulConfigDataNoImportIntegrationTests.java
Labels: bug
